"""Change a chain parameter by consortium vote.

Params only applies a change once 3 of the 4 validators approve it, so no
single organisation can quietly make confirmation easier or fraud cheaper. This
script casts those votes from the validators' own keys and shows each approval
landing, which is the on-chain governance the thesis argues for.

    python -m src.car.govern --show
    python -m src.car.govern --set T_pending=60
    python -m src.car.govern --set k_confirm=2 T_pending=60
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from src.car.chain import CHAIN_DIR, Chain, admin_key  # noqa: E402

SHOWN = ["k_confirm", "T_pending", "T_reward_window", "stake",
         "registration_bond", "m_checkback", "match_radius_m", "N_rewarded"]


def validator_keys(consortium: list[str]) -> dict[str, str]:
    """Private key for each consortium address that we can find on disk.

    Validator 1 is the deployer, whose key is in besu/.env. The others were
    generated by Besu into besu/networkFiles/keys/<address>/key.
    """
    keys: dict[str, str] = {}
    dep = admin_key()
    from eth_account import Account
    keys[Account.from_key(dep).address.lower()] = dep

    kdir = CHAIN_DIR / "besu" / "networkFiles" / "keys"
    if kdir.exists():
        for d in kdir.iterdir():
            kf = d / "key"
            if d.is_dir() and kf.exists():
                k = kf.read_text().strip()
                k = k if k.startswith("0x") else "0x" + k
                keys[Account.from_key(k).address.lower()] = k
    return {a: keys[a.lower()] for a in consortium if a.lower() in keys}


def show(ch: Chain) -> None:
    p = ch.c["Params"]
    print("current parameters")
    for n in SHOWN:
        try:
            print(f"  {n:20} {p.functions.get(n).call()}")
        except Exception:                                      # noqa: BLE001
            pass


def set_param(name: str, value: int, consortium: list[str],
              keys: dict[str, str]) -> bool:
    reader = Chain()
    p = reader.c["Params"]
    need = p.functions.APPROVALS_REQUIRED().call()
    old = p.functions.get(name).call()
    print(f"\n{name}: {old} -> {value}   (needs {need} of {len(consortium)} approvals)")
    if old == value:
        print("  already set, nothing to do")
        return True

    voters = [a for a in consortium if a in keys]
    if len(voters) < need:
        print(f"  only {len(voters)} validator keys found on disk; need {need}.")
        print(f"  Keys are read from chain/besu/.env and "
              f"chain/besu/networkFiles/keys/.")
        return False

    for addr in voters:
        ch = Chain(keys[addr])
        fn = ch.c["Params"].functions.approveParam(name, value)
        why = ch.dry_run(fn)
        if why:
            print(f"  {addr[:10]}…  refused: {why}")
            continue
        r = ch.send(fn)
        now = reader.c["Params"].functions.get(name).call()
        print(f"  {addr[:10]}…  approved  gas {r['gas_used']:>6}  "
              f"block {r['block']}  -> value now {now}")
        if now == value:
            break

    final = p.functions.get(name).call()
    ok = final == value
    print(f"  {'APPLIED' if ok else 'NOT APPLIED'}: {name} = {final}")
    return ok


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--set", nargs="*", default=[], metavar="NAME=VALUE")
    ap.add_argument("--show", action="store_true")
    args = ap.parse_args()

    ch = Chain()
    consortium = [ch.w3.to_checksum_address(a) for a in ch.dep["consortium"]]
    if args.show or not args.set:
        show(ch)
        if not args.set:
            return

    keys = validator_keys(consortium)
    print(f"\nconsortium {len(consortium)} members, keys found for {len(keys)}")
    ok = True
    for item in args.set:
        name, _, v = item.partition("=")
        if not v:
            raise SystemExit(f"bad --set {item!r}; use NAME=VALUE")
        ok &= set_param(name.strip(), int(v), consortium, keys)
    print()
    show(ch)
    if not ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
