// Turn Besu's generated network files into four ready-to-run node directories.
//
// Besu's own generator produces the genesis (with correctly RLP-encoded QBFT
// extraData) and one key pair per validator. Hand-writing that extraData is a
// well-known way to get a chain that starts and then never produces a block,
// so it is never done here.
//
// What this adds is the wiring the generator leaves out: each node's directory,
// its private key, and a static-nodes.json listing the other three.
//
// Those entries use IP addresses, not container names. Besu's static-nodes
// parser rejects DNS names in enode URLs — with `besu-node2` in the file every
// node exits at startup with "Illegal static enode supplied". The IPs are
// pinned in docker-compose.yml and must match BASE_IP below.
//
//   node besu/prepare.js

const fs = require("fs");
const path = require("path");

const BESU = __dirname;
const NET = path.join(BESU, "networkFiles");
const NODES = path.join(BESU, "nodes");
const P2P_PORT = 30303;
// 172.28.0.11 .. .14, matching the ipv4_address entries in docker-compose.yml
const SUBNET = "172.28.0.";
const FIRST_HOST = 11;

function fail(msg) {
  console.error(`\n${msg}\n`);
  process.exit(1);
}

if (!fs.existsSync(NET)) {
  fail(`networkFiles not found at ${NET}\n` +
       `Run the generator first:\n` +
       `  docker run --rm -v "%cd%/besu:/cfg" hyperledger/besu:latest \\\n` +
       `    operator generate-blockchain-config \\\n` +
       `    --config-file=/cfg/qbft-config.json --to=/cfg/networkFiles \\\n` +
       `    --private-key-file-name=key`);
}

const genesis = path.join(NET, "genesis.json");
if (!fs.existsSync(genesis)) fail(`no genesis.json in ${NET}`);

const g = JSON.parse(fs.readFileSync(genesis, "utf8"));
if (!g.extraData || g.extraData.length < 100) {
  fail(`genesis extraData looks wrong (${g.extraData}). Regenerate the config.`);
}

const keyDir = path.join(NET, "keys");
const addresses = fs.readdirSync(keyDir).filter((d) =>
  fs.statSync(path.join(keyDir, d)).isDirectory());
if (addresses.length !== 4) {
  fail(`expected 4 validator key folders, found ${addresses.length}`);
}

const nodes = addresses.map((addr, i) => {
  const pub = fs.readFileSync(path.join(keyDir, addr, "key.pub"), "utf8").trim();
  const id = pub.replace(/^0x/, "");
  // Besu accepts exactly 128 hex characters; anything else is rejected at parse
  if (!/^[0-9a-fA-F]{128}$/.test(id)) {
    fail(`key.pub for ${addr} is not a 128-character hex id (got ${id.length})`);
  }
  return { addr, id, ip: `${SUBNET}${FIRST_HOST + i}`, index: i + 1 };
});

fs.rmSync(NODES, { recursive: true, force: true });
for (const n of nodes) {
  const dir = path.join(NODES, `node${n.index}`);
  fs.mkdirSync(path.join(dir, "data"), { recursive: true });
  fs.copyFileSync(path.join(keyDir, n.addr, "key"), path.join(dir, "data", "key"));
  const peers = nodes
    .filter((o) => o.index !== n.index)
    .map((o) => `enode://${o.id}@${o.ip}:${P2P_PORT}`);
  fs.writeFileSync(path.join(dir, "data", "static-nodes.json"),
                   JSON.stringify(peers, null, 2));
  console.log(`node${n.index}  ${n.ip}  ${n.addr}  ${peers.length} peers`);
}

fs.copyFileSync(genesis, path.join(BESU, "genesis.json"));

const env = [
  `# generated by besu/prepare.js`,
  `BESU_CHAIN_ID=${g.config.chainId}`,
  `VALIDATOR_1=${nodes[0].addr}`,
  `VALIDATOR_2=${nodes[1].addr}`,
  `VALIDATOR_3=${nodes[2].addr}`,
  `VALIDATOR_4=${nodes[3].addr}`,
  ``,
  `# private key of validator 1, used by Hardhat to deploy`,
  `DEPLOYER_KEY=0x${fs.readFileSync(
    path.join(keyDir, nodes[0].addr, "key"), "utf8").trim().replace(/^0x/, "")}`,
].join("\n");
fs.writeFileSync(path.join(BESU, ".env"), env + "\n");

console.log(`\ngenesis   -> ${path.join(BESU, "genesis.json")}`);
console.log(`node dirs -> ${NODES}`);
console.log(`env       -> ${path.join(BESU, ".env")}  (holds a private key; do not commit)`);
console.log(`\nNext:  docker compose -f besu/docker-compose.yml up -d`);
