// Generate a separate key for each role and append them to besu/.env.
//
// On Besu there is one funded key, so deploy.js gave every role to the admin
// address. That is fine for a smoke test and wrong for the experiments: the
// unlearning certificate and its audit must come from different parties, or
// the separation UnlearningLog enforces is cosmetic. Same for the FL server,
// the keeper, the repair team and merchants.
//
// Gas is free on this chain, so these keys need no balance.
//
//   node scripts/roles.js            # generate and append to besu/.env
//   node scripts/roles.js --show     # print what is already there
//
// Then redeploy so the roles are assigned to them:
//   npx hardhat run scripts/deploy.js --network besu

const fs = require("fs");
const path = require("path");
const { ethers } = require("ethers");

const ENV = path.join(__dirname, "..", "besu", ".env");
const ROLES = ["FL_SERVER", "UNLEARN_SERVICE", "AUDITOR", "KEEPER",
               "REPAIR", "MERCHANT"];

const existing = fs.existsSync(ENV) ? fs.readFileSync(ENV, "utf8") : "";
if (!existing) {
  console.error(`${ENV} not found — run node besu/prepare.js first`);
  process.exit(1);
}

if (process.argv.includes("--show")) {
  for (const r of ROLES) {
    const m = existing.match(new RegExp(`^${r}_ADDRESS=(.*)$`, "m"));
    console.log(`  ${r.padEnd(16)} ${m ? m[1] : "(not set)"}`);
  }
  process.exit(0);
}

const already = ROLES.filter(r =>
  new RegExp(`^${r}_ADDRESS=`, "m").test(existing));
if (already.length) {
  console.error(`besu/.env already defines: ${already.join(", ")}`);
  console.error("Remove those lines first if you really want new keys — " +
                "regenerating them would orphan any role already granted " +
                "on-chain to the old addresses.");
  process.exit(1);
}

const lines = ["", "# role keys, generated by scripts/roles.js",
               "# gas is free on this chain, so these need no balance"];
console.log("generated role accounts\n");
for (const r of ROLES) {
  const w = ethers.Wallet.createRandom();
  lines.push(`${r}_ADDRESS=${w.address}`);
  lines.push(`${r}_KEY=${w.privateKey}`);
  console.log(`  ${r.padEnd(16)} ${w.address}`);
}
fs.appendFileSync(ENV, lines.join("\n") + "\n");

console.log(`\nappended to ${ENV}`);
console.log("That file now holds seven private keys. Keep it out of git.");
console.log("\nNext: npx hardhat run scripts/deploy.js --network besu");
console.log("Roles will go to these addresses instead of the admin key, so the");
console.log("auditor really is a different party from the unlearning service.");
